### ISSUE TITLE
Dependencies & Licenses Module

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordSpezi/.github#42]
### Problem

The current [SpeziTemplateApplication](https://github.com/StanfordSpezi/SpeziTemplateApplication) includes an automated setup to populate a list of dependencies and accompanying licenses base on the Swift Package dependencies based on https://github.com/FelixHerrmann/swift-package-list and the work done by @NikolaiMadlener.

Replicating this functionality outside of the Template Application is challenging and requires one to manually copy code.

### Solution

The functionality should move into its own Spezi Module that allows one to use the functionality in multiple applications.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by NikolaiMadlener** [comment]
Would love to refactor this from the template app to its own separate module! Could you create the repo for it @PSchmiedmayer ?

**Comment by PSchmiedmayer** [comment]
@NikolaiMadlener Sorry for the late response here! I have created the repo here and gave you permissions to work on it: https://github.com/StanfordSpezi/SpeziLicense

**Comment by PSchmiedmayer** [comment]
This issue has been addressed with tagging 0.1.0 in https://github.com/StanfordSpezi/SpeziLicense; thank you @NikolaiMadlener!
